version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: nestjs_crud_api
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db/nestjs_crud_api
    ports:
      - '3000:3000'
    depends_on:
      - db